name: Deploy Laravel to Serverplan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Laravel project via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: remedic.it
          username: mremedik
          port: 10223
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/mremedik/public_html/api"
          strip_components: 0
          rm: true
          overwrite: true
          exclude: |
            /.phpunit.cache
            /node_modules
            /public/hot
            /public/storage
            /storage/*.key
            /storage/pail
            /vendor
            .env
            .env.backup
            .env.production
            .phpactor.json
            .phpunit.result.cache
            Homestead.json
            Homestead.yaml
            npm-debug.log
            yarn-error.log
            /auth.json
            /.fleet
            /.idea
            /.nova
            /.vscode
            /.zed
