name: Deploy to Serverplan

on:
  push:
    branches:
      - main # o il branch che usi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        run: |
          ssh remedic "cd /home/mremedik/laravel-project && git pull origin main && composer install --no-dev --prefer-dist && php artisan migrate --force"
