name: Deploy to Serverplan

on:
  push:
    branches:
      - main # o il branch che usi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -p 10223 remedic.it >> $HOME/.ssh/known_hosts
          echo "Host remedic" >> $HOME/.ssh/config
          echo "  HostName remedic.it" >> $HOME/.ssh/config
          echo "  Port 10223" >> $HOME/.ssh/config
          echo "  User mremedik" >> $HOME/.ssh/config
          echo "  IdentityFile $HOME/.ssh/id_rsa" >> $HOME/.ssh/config

      - name: Deploy via SSH
        run: |
          ssh remedic "cd /home/mremedik/laravel-project && git pull origin main && composer install --no-dev --prefer-dist && php artisan migrate --force"
